server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.159.129:3306/leyou
    username: root
    password: root
  redis:
    host: 192.168.159.129
  rabbitmq:
    host: 192.168.159.129
    port: 5672
    username: leyou
    password: leyou
    virtual-host: /leyou
mybatis:
  type-aliases-package: com.leyou.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15